'#!/bin/bash' 
'set -e' 
'echo "=============================="' 
'echo "  BUNNA START.SH IS RUNNING"' 
'echo "=============================="' 
'php artisan config:clear' 
'php artisan route:clear' 
'php artisan cache:clear' 
'echo ">>> Attempting DB connection..."' 
'echo ">>> Starting Apache..."' 
'apache2-foreground' 
